# Stage 1: Build the app
FROM node:23-alpine3.20 AS build
WORKDIR /JobFitChecker/Jobfit-Checker-Frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve with NGINX
FROM nginx:alpine
COPY --from=build /JobFitChecker/Jobfit-Checker-Frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
